package main

import (
	"flag"
	"fmt"
	"sort"
	"strings"
)

// ================================================================
// Shell completion (--completion bash|zsh|fish)
// ================================================================
//
// The completion scripts are GENERATED from the same registerFlags source
// the binary uses to declare its CLI — the same hermetic trick the usage
// parity test uses, turned into a product feature: a flag added to
// registerFlags shows up in the next completion script with zero extra
// work, and the completion can never advertise a flag the binary does not
// accept (or forget one it does). Descriptions come from the flag usage
// strings, trimmed to one line.

// completionFlagNames returns every registered flag name (sorted) with its
// one-line description, read from a private FlagSet built through
// registerFlags — never from process-global state.
func completionFlagNames() [][2]string {
	fs := flag.NewFlagSet("completion", flag.ContinueOnError)
	registerFlags(fs, new(Options), new(string), new(bool))
	names := []string{}
	byName := map[string]string{}
	fs.VisitAll(func(fl *flag.Flag) {
		names = append(names, fl.Name)
		// first line of the usage string, trimmed — completion tooltips
		// have room for a sentence, not a paragraph
		desc := fl.Usage
		if i := strings.IndexByte(desc, '\n'); i >= 0 {
			desc = desc[:i]
		}
		byName[fl.Name] = strings.TrimSpace(desc)
	})
	sort.Strings(names)
	out := make([][2]string, 0, len(names)+1)
	for _, n := range names {
		out = append(out, [2]string{n, byName[n]})
	}
	// --help is served by the flag package itself; the completion must
	// offer it anyway.
	out = append(out, [2]string{"help", "show this help"})
	return out
}

// printCompletion writes the completion script for the requested shell to
// stdout. Unknown shells are an error (exit 2 at the caller) — silently
// printing bash syntax into a zshrc would be the dishonest kind of help.
func printCompletion(shell string) error {
	flags := completionFlagNames()
	switch strings.ToLower(shell) {
	case "bash":
		fmt.Println("# bash completion for autoprivilege (generated by --completion bash)")
		fmt.Println("_autoprivilege_completions() {")
		fmt.Println("  local cur=\"${COMP_WORDS[COMP_CWORD]}\"")
		fmt.Println("  local opts=\"" + bashFlagList(flags) + "\"")
		fmt.Println("  COMPREPLY=()")
		fmt.Println("  [[ $cur == -* ]] && COMPREPLY=( $(compgen -W \"$opts\" -- \"$cur\") )")
		fmt.Println("}")
		fmt.Println("complete -F _autoprivilege_completions autoprivilege")
		return nil
	case "zsh":
		fmt.Println("#compdef autoprivilege")
		fmt.Println("# zsh completion for autoprivilege (generated by --completion zsh)")
		fmt.Println("_arguments \\")
		for i, f := range flags {
			sep := " \\"
			if i == len(flags)-1 {
				sep = ""
			}
			fmt.Printf("  '%s[%s]'%s\n", zshOptSpec(f[0]), zshEscape(f[1]), sep)
		}
		return nil
	case "fish":
		fmt.Println("# fish completion for autoprivilege (generated by --completion fish)")
		for _, f := range flags {
			fmt.Printf("complete -c autoprivilege -l %s -d '%s'\n", f[0], fishEscape(f[1]))
		}
		return nil
	}
	return fmt.Errorf("unknown shell %q (valid: bash, zsh, fish)", shell)
}

func bashFlagList(flags [][2]string) string {
	parts := make([]string, 0, len(flags))
	for _, f := range flags {
		parts = append(parts, "--"+f[0])
	}
	return strings.Join(parts, " ")
}

func zshOptSpec(name string) string {
	// long option only — every flag has one, and the short -h is served
	// by the flag package's default handling
	return "(--" + name + ")" + "\"--" + name + "\""
}

func zshEscape(s string) string {
	return strings.NewReplacer("'", "'\\''", "[", "\\[", "]", "\\]").Replace(s)
}

func fishEscape(s string) string {
	return strings.NewReplacer("'", "\\'").Replace(s)
}
