package main

import (
	"flag"
	"fmt"
	"sort"
	"strings"
)

// ================================================================
// Shell completion (--completion bash|zsh|fish)
// ================================================================
//
// The completion scripts are GENERATED from the same registerFlags source
// the binary uses to declare its CLI — the same hermetic trick the usage
// parity test uses, turned into a product feature: a flag added to
// registerFlags shows up in the next completion script with zero extra
// work, and the completion can never advertise a flag the binary does not
// accept (or forget one it does). Descriptions come from the flag usage
// strings, trimmed to one line.
//
// Round 14: value completion. Flags whose argument has a CLOSED set of
// valid values (--risk, --fail-on, --vector, --explain, ...) complete the
// VALUE too — every value list is sourced from the binary's own tables
// (vectorCatalogOrder, validSources, the same literals run() validates
// against), so the completion can never suggest a value the tool rejects.

// completionFlagNames returns every registered flag name (sorted) with its
// one-line description, read from a private FlagSet built through
// registerFlags — never from process-global state.
func completionFlagNames() [][2]string {
	fs := flag.NewFlagSet("completion", flag.ContinueOnError)
	registerFlags(fs, new(Options), new(string), new(bool))
	names := []string{}
	byName := map[string]string{}
	fs.VisitAll(func(fl *flag.Flag) {
		names = append(names, fl.Name)
		// first line of the usage string, trimmed — completion tooltips
		// have room for a sentence, not a paragraph
		desc := fl.Usage
		if i := strings.IndexByte(desc, '\n'); i >= 0 {
			desc = desc[:i]
		}
		byName[fl.Name] = strings.TrimSpace(desc)
	})
	sort.Strings(names)
	out := make([][2]string, 0, len(names)+1)
	for _, n := range names {
		out = append(out, [2]string{n, byName[n]})
	}
	// --help is served by the flag package itself; the completion must
	// offer it anyway.
	out = append(out, [2]string{"help", "show this help"})
	return out
}

// completionValues maps flags whose argument has a CLOSED set of valid
// values to those values — the completion completes the VALUE, not just the
// flag. Everything is sourced from the binary's own tables (no hardcoded
// drift): vector names from vectorCatalogOrder, sources from validSources,
// shells and risk levels from the same literals run() validates against.
var completionValues = map[string][]string{
	"risk":        {"safe", "low", "medium", "high", "danger"},
	"fail-on":     {"low", "medium", "high", "danger"},
	"fail-on-new": {"low", "medium", "high", "danger"},
	"log":         {"text", "json"},
	"completion":  {"bash", "zsh", "fish"},
	"vector":      append(append([]string{}, vectorCatalogOrder...), "all"),
	"explain":     append([]string{"all"}, validSources...),
}

// completionScriptFor renders the full completion script for one shell.
// Split from printCompletion so the renderer is a pure function (and tests
// can pin the shape of each dialect without capturing stdout).
func completionScriptFor(shell string) (string, error) {
	flags := completionFlagNames()
	var b strings.Builder
	switch strings.ToLower(shell) {
	case "bash":
		b.WriteString("# bash completion for autoprivilege (generated by --completion bash)\n")
		b.WriteString("_autoprivilege_completions() {\n")
		b.WriteString("  local cur=\"${COMP_WORDS[COMP_CWORD]}\"\n")
		b.WriteString("  local prev=\"${COMP_WORDS[COMP_CWORD-1]}\"\n")
		b.WriteString("  local opts=\"" + bashFlagList(flags) + "\"\n")
		b.WriteString("  COMPREPLY=()\n")
		// value completion first: a flag with a closed value set completes
		// its values, so `--risk <TAB>` offers safe|low|medium|high|danger
		b.WriteString("  case \"$prev\" in\n")
		for _, pair := range sortedCompletionValues() {
			b.WriteString(fmt.Sprintf("    --%s) COMPREPLY=( $(compgen -W \"%s\" -- \"$cur\") ); return ;;\n",
				pair.name, strings.Join(pair.values, " ")))
		}
		b.WriteString("  esac\n")
		b.WriteString("  [[ $cur == -* ]] && COMPREPLY=( $(compgen -W \"$opts\" -- \"$cur\") )\n")
		b.WriteString("}\n")
		b.WriteString("complete -F _autoprivilege_completions autoprivilege\n")
		return b.String(), nil
	case "zsh":
		b.WriteString("#compdef autoprivilege\n")
		b.WriteString("# zsh completion for autoprivilege (generated by --completion zsh)\n")
		b.WriteString("_arguments \\\n")
		for i, f := range flags {
			sep := " \\"
			if i == len(flags)-1 {
				sep = ""
			}
			if vals, ok := completionValues[f[0]]; ok {
				b.WriteString(fmt.Sprintf("  '(%s)--%s[%s]:%s:(%s)'%s\n",
					"--"+f[0], f[0], zshEscape(f[1]), f[0], strings.Join(vals, " "), sep))
			} else {
				b.WriteString(fmt.Sprintf("  '%s[%s]'%s\n", zshOptSpec(f[0]), zshEscape(f[1]), sep))
			}
		}
		return b.String(), nil
	case "fish":
		b.WriteString("# fish completion for autoprivilege (generated by --completion fish)\n")
		for _, f := range flags {
			if vals, ok := completionValues[f[0]]; ok {
				b.WriteString(fmt.Sprintf("complete -c autoprivilege -l %s -x -a '%s' -d '%s'\n",
					f[0], strings.Join(fishEscapeList(vals), " "), fishEscape(f[1])))
			} else {
				b.WriteString(fmt.Sprintf("complete -c autoprivilege -l %s -d '%s'\n", f[0], fishEscape(f[1])))
			}
		}
		return b.String(), nil
	}
	return "", fmt.Errorf("unknown shell %q (valid: bash, zsh, fish)", shell)
}

// sortedCompletionValues gives the value map a deterministic order (map
// iteration would render the bash case statement differently per run).
func sortedCompletionValues() []completionValuesEntry {
	names := make([]string, 0, len(completionValues))
	for name := range completionValues {
		names = append(names, name)
	}
	sort.Strings(names)
	out := make([]completionValuesEntry, 0, len(names))
	for _, n := range names {
		out = append(out, completionValuesEntry{name: n, values: completionValues[n]})
	}
	return out
}

type completionValuesEntry struct {
	name   string
	values []string
}

func fishEscapeList(vals []string) []string {
	out := make([]string, len(vals))
	for i, v := range vals {
		out[i] = fishEscape(v)
	}
	return out
}

func bashFlagList(flags [][2]string) string {
	parts := make([]string, 0, len(flags))
	for _, f := range flags {
		parts = append(parts, "--"+f[0])
	}
	return strings.Join(parts, " ")
}

func zshOptSpec(name string) string {
	// long option only — every flag has one, and the short -h is served
	// by the flag package's default handling
	return "(--" + name + ")" + "\"--" + name + "\""
}

func zshEscape(s string) string {
	return strings.NewReplacer("'", "'\\''", "[", "\\[", "]", "\\]").Replace(s)
}

func fishEscape(s string) string {
	return strings.NewReplacer("'", "\\'").Replace(s)
}

// printCompletion writes the completion script for the requested shell to
// stdout. Unknown shells are an error (exit 2 at the caller) — silently
// printing bash syntax into a zshrc would be the dishonest kind of help.
func printCompletion(shell string) error {
	script, err := completionScriptFor(shell)
	if err != nil {
		return err
	}
	fmt.Print(script)
	return nil
}
